### ISSUE TITLE
Console errors when running `yarn test`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#218]
**Describe the bug**
When the test command is run we get a series of these errors:

`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`

**To Reproduce**
In the root of your local talawa-admin repo run these commands:
```
yarn install
yarn test --watchAll=false --coverage
```
The errors will be very visible if you scroll upwards after the testing is complete.

**Expected behavior**
No console errors

**Actual behavior**
When the command is run we get a series of these errors:

`Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.`

**Screenshots**
See below

```
console.error
      Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.
          at p
          at p
          at div
          at div
          at Col (/home/xxx/talawa-admin/node_modules/react-bootstrap/cjs/Col.js:23:23)
          at div
          at Row (/home/xxx/talawa-admin/node_modules/react-bootstrap/cjs/Row.js:25:23)
          at SuperDashListCard (/home/xxx/talawa-admin/src/components/SuperDashListCard/SuperDashListCard.tsx:24:16)
          at div
          at div
          at div
          at Col (/home/xxx/talawa-admin/node_modules/react-bootstrap/cjs/Col.js:23:23)
          at div
          at Row (/home/xxx/talawa-admin/node_modules/react-bootstrap/cjs/Row.js:25:23)
          at OrgList (/home/xxx/talawa-admin/src/screens/OrgList/OrgList.tsx:19:47)
          at Provider (/home/xxx/talawa-admin/node_modules/react-redux/lib/components/Provider.js:23:20)
          at ApolloProvider (/home/xxx/talawa-admin/node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
          at MockedProvider (/home/xxx/talawa-admin/node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)

```

**Additional details**

**Comment by Devesh21700Kumar** [comment]
Its happening in those instances of components where <p> tag is nested inside a <p> tag

For example:- 
![image](https://user-images.githubusercontent.com/59202075/148725752-af0d3269-c783-495b-8089-01906eee185f.png)

Since <p> tags should not have an inline tag nested inside of them, I think the solution is that the nested <p> tags inside any <p> tag should be removed should be removed

**Comment by palisadoes** [comment]
Do you want to work on this? The errors are caused by us not following a best practice.

**Comment by Devesh21700Kumar** [comment]
> Do you want to work on this? The errors are caused by us not following a best practice.

Yes
